// <auto-generated />
using FilmCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollection.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    [Migration("20220203002959_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FilmCollection.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("category");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            categoryName = "Action/Adventure"
                        },
                        new
                        {
                            categoryId = 2,
                            categoryName = "Comedy"
                        },
                        new
                        {
                            categoryId = 3,
                            categoryName = "Drama"
                        },
                        new
                        {
                            categoryId = 4,
                            categoryName = "Family"
                        },
                        new
                        {
                            categoryId = 5,
                            categoryName = "Horror/Suspense"
                        },
                        new
                        {
                            categoryId = 6,
                            categoryName = "Miscellaneous"
                        },
                        new
                        {
                            categoryId = 7,
                            categoryName = "Romance"
                        },
                        new
                        {
                            categoryId = 8,
                            categoryName = "Television"
                        },
                        new
                        {
                            categoryId = 9,
                            categoryName = "VHS"
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.Movies", b =>
                {
                    b.Property<int>("movieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movieId");

                    b.HasIndex("categoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            movieId = 1,
                            categoryId = 1,
                            director = "Anthony & Joe Russo",
                            edited = false,
                            lentTo = "",
                            notes = "Best Captain America movie.",
                            rating = "PG-13",
                            title = "Captain America Winter Soldier",
                            year = 2014
                        },
                        new
                        {
                            movieId = 2,
                            categoryId = 7,
                            director = "Rob Reiner",
                            edited = false,
                            lentTo = "Shannon",
                            notes = "One of the greatest movies ever. End of story.",
                            rating = "PG",
                            title = "The Princess Bride",
                            year = 1987
                        },
                        new
                        {
                            movieId = 3,
                            categoryId = 7,
                            director = "John Turteltaub",
                            edited = false,
                            lentTo = "",
                            notes = "",
                            rating = "PG",
                            title = "While you were Sleeping",
                            year = 1995
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.Movies", b =>
                {
                    b.HasOne("FilmCollection.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
