// <auto-generated />
using FilmCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollection.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    partial class FilmCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FilmCollection.Models.Movies", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            category = "Action/Adventure",
                            director = "Anthony & Joe Russo",
                            edited = false,
                            lentTo = "",
                            notes = "Best Captain America movie.",
                            rating = "PG-13",
                            title = "Captain America Winter Soldier",
                            year = 2014
                        },
                        new
                        {
                            MovieId = 2,
                            category = "Romance",
                            director = "Rob Reiner",
                            edited = false,
                            lentTo = "Shannon",
                            notes = "One of the greatest movies ever. End of story.",
                            rating = "PG",
                            title = "The Princess Bride",
                            year = 1987
                        },
                        new
                        {
                            MovieId = 3,
                            category = "Rom-Com",
                            director = "John Turteltaub",
                            edited = false,
                            lentTo = "",
                            notes = "",
                            rating = "PG",
                            title = "While you were Sleeping",
                            year = 1995
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
